- hosts: all
  become: yes
  tasks:
    - name: update packages to latest version
      apt: upgrade=dist update_cache=yes

    - name: install required apt packages
      apt: name={{ item }}
      with_items:
        - "{{ apt_packages }}"
