"""init

Revision ID: a99a47a1a103
Revises: 
Create Date: 2017-03-11 10:02:41.083275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99a47a1a103'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zhuhao_registrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('company', sa.Unicode(), nullable=False),
    sa.Column('job_title', sa.Unicode(), nullable=True),
    sa.Column('contact_way', sa.Unicode(), nullable=False),
    sa.Column('main_industry', sa.Unicode(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zhuhao_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zhuhao_users')
    op.drop_table('zhuhao_registrations')
    # ### end Alembic commands ###
